name: Django CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          SECRET_KEY: dummy
          DEBUG: 'True'
          HH_CLIENT_ID: dummy
          HH_CLIENT_SECRET: dummy
          HOST: example.com
        run: |
          python manage.py test

